project_id = "gqdvwmwueaqyqepwyifk"

[functions.turkish-chat]
verify_jwt = false

[functions.analyze-project]
verify_jwt = true

[functions.generate-questions]
verify_jwt = true

[functions.send-invitation-email]
verify_jwt = false

[functions.searcho-realtime]
verify_jwt = false