project_id = "elbokywmphjwmqunaoqc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "dual"
max_concurrent_users = 200

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[edge_functions]
enabled = true

[functions.analyze-project]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false