export const TURKISH_ORTHOGRAPHY_PROMPT = `Kritik dil kuralı: Kullanıcıya görünen tüm Türkçe metinleri, özellikle soru metinlerini, eksiksiz Türkçe karakterlerle yaz. "cok", "nasil", "gorusme", "arastirma", "kullanici" gibi ASCII transliterasyon kullanma; "çok", "nasıl", "görüşme", "araştırma", "kullanıcı" yaz.`;

const WORD_REPLACEMENTS: Record<string, string> = {
  acik: "açık",
  acikca: "açıkça",
  aciklama: "açıklama",
  aciklamalar: "açıklamalar",
  aciklamak: "açıklamak",
  acikligi: "açıklığı",
  aciklik: "açıklık",
  acilis: "açılış",
  acisindan: "açısından",
  adim: "adım",
  adimi: "adımı",
  adimda: "adımda",
  adimlarda: "adımlarda",
  adimlari: "adımları",
  adimlarini: "adımlarını",
  agirlik: "ağırlık",
  akilli: "akıllı",
  akis: "akış",
  akisi: "akışı",
  akisinda: "akışında",
  akisini: "akışını",
  aklinizda: "aklınızda",
  aklinizdan: "aklınızdan",
  aklinizi: "aklınızı",
  alacaginiz: "alacağınız",
  alani: "alanı",
  alaninda: "alanında",
  algi: "algı",
  algilama: "algılama",
  algisi: "algısı",
  aliskanlik: "alışkanlık",
  aliskanliklari: "alışkanlıkları",
  aliskanliklariniz: "alışkanlıklarınız",
  alisveris: "alışveriş",
  alisveriste: "alışverişte",
  anladiginiz: "anladığınız",
  anlamli: "anlamlı",
  anlasilir: "anlaşılır",
  anlasilirlik: "anlaşılırlık",
  anlatir: "anlatır",
  anlatirsiniz: "anlatırsınız",
  "anlatir misiniz": "anlatır mısınız",
  anlatmak: "anlatmak",
  araci: "aracı",
  araclari: "araçları",
  arastirma: "araştırma",
  arastirmak: "araştırmak",
  arastirmalar: "araştırmalar",
  arastirmalari: "araştırmaları",
  arastirmalarin: "araştırmaların",
  arastirmalarini: "araştırmalarını",
  arastirmasi: "araştırması",
  arastirmasinda: "araştırmasında",
  arastirmasini: "araştırmasını",
  arastirmaya: "araştırmaya",
  arastirmayi: "araştırmayı",
  ayrica: "ayrıca",
  ayiran: "ayıran",
  baglam: "bağlam",
  baglama: "bağlama",
  baglami: "bağlamı",
  baglaminda: "bağlamında",
  baglamini: "bağlamını",
  bagli: "bağlı",
  baglanti: "bağlantı",
  baglantisi: "bağlantısı",
  basari: "başarı",
  basarili: "başarılı",
  basarisiz: "başarısız",
  baslangic: "başlangıç",
  basligi: "başlığı",
  baslik: "başlık",
  basliklari: "başlıkları",
  basvurusu: "başvurusu",
  begendiginiz: "beğendiğiniz",
  belirgin: "belirgin",
  belirsiz: "belirsiz",
  beklenti: "beklenti",
  beklentiniz: "beklentiniz",
  bildirim: "bildirim",
  bildirimleri: "bildirimleri",
  bilgilendirici: "bilgilendirici",
  bolum: "bölüm",
  bolume: "bölüme",
  bolumu: "bölümü",
  bolumleri: "bölümleri",
  bolumlerde: "bölümlerde",
  bos: "boş",
  calisma: "çalışma",
  calismasi: "çalışması",
  calistigina: "çalıştığına",
  calistigini: "çalıştığını",
  calistiginda: "çalıştığında",
  cikar: "çıkar",
  cikiyor: "çıkıyor",
  cikti: "çıktı",
  cok: "çok",
  coklu: "çoklu",
  cozum: "çözüm",
  degdigi: "değdiği",
  deger: "değer",
  degerlendirme: "değerlendirme",
  degerlendirirken: "değerlendirirken",
  degerlendirmeniz: "değerlendirmeniz",
  degil: "değil",
  degilse: "değilse",
  degisen: "değişen",
  degisik: "değişik",
  degisiklik: "değişiklik",
  degisiklikleri: "değişiklikleri",
  degistirebilseydiniz: "değiştirebilseydiniz",
  degismesini: "değişmesini",
  deneyimi: "deneyimi",
  deneyiminde: "deneyiminde",
  deneyiminiz: "deneyiminiz",
  detayli: "detaylı",
  diger: "diğer",
  dogal: "doğal",
  dogrudan: "doğrudan",
  dogru: "doğru",
  donusum: "dönüşüm",
  dusunce: "düşünce",
  dusunceler: "düşünceler",
  dusunurken: "düşünürken",
  dusunmeye: "düşünmeye",
  dusundugunuzde: "düşündüğünüzde",
  duzey: "düzey",
  duzeyi: "düzeyi",
  etkilestiginizde: "etkileştiğinizde",
  farkindalik: "farkındalık",
  farkli: "farklı",
  firsat: "fırsat",
  firsatlari: "fırsatları",
  gec: "geç",
  gececegiz: "geçeceğiz",
  gecelim: "geçelim",
  gecen: "geçen",
  geciyor: "geçiyor",
  gecirdiginiz: "geçirdiğiniz",
  gecerli: "geçerli",
  gecmis: "geçmiş",
  gelistirirken: "geliştirirken",
  gelistirme: "geliştirme",
  gerektigini: "gerektiğini",
  getiri: "getiri",
  giris: "giriş",
  gore: "göre",
  gorev: "görev",
  gorevi: "görevi",
  gorevin: "görevin",
  gorevinizde: "görevinizde",
  gorevde: "görevde",
  gorevleri: "görevleri",
  gordugunuz: "gördüğünüz",
  gordugunuzde: "gördüğünüzde",
  gorunuyor: "görünüyor",
  gorunumu: "görünümü",
  gorus: "görüş",
  gorusme: "görüşme",
  gorusmesi: "görüşmesi",
  gorusmeler: "görüşmeler",
  gorusmeleri: "görüşmeleri",
  gorusmelerinde: "görüşmelerinde",
  gorustugunuz: "görüştüğünüz",
  guven: "güven",
  guvenilir: "güvenilir",
  gun: "gün",
  guncel: "güncel",
  guncelle: "güncelle",
  guncellenmis: "güncellenmiş",
  gunde: "günde",
  gundelik: "gündelik",
  gunluk: "günlük",
  gunu: "günü",
  gununuz: "gününüz",
  gununuzde: "gününüzde",
  gununuzu: "gününüzü",
  hazir: "hazır",
  hazirladim: "hazırladım",
  hazirlamak: "hazırlamak",
  hazirlanacak: "hazırlanacak",
  hesabi: "hesabı",
  hesabiniz: "hesabınız",
  hesabinizda: "hesabınızda",
  hesabini: "hesabını",
  hesabinin: "hesabının",
  ic: "iç",
  ice: "içe",
  iceri: "içeri",
  icerik: "içerik",
  iceriyor: "içeriyor",
  icerisinde: "içerisinde",
  icin: "için",
  icinde: "içinde",
  ihtiyac: "ihtiyaç",
  ihtiyacinda: "ihtiyacında",
  ihtiyaciniz: "ihtiyacınız",
  iki: "iki",
  iliski: "ilişki",
  ilgili: "ilgili",
  ilk: "ilk",
  ipucu: "ipucu",
  is: "iş",
  isaret: "işaret",
  isaretler: "işaretler",
  isaretleri: "işaretleri",
  isiniyor: "ısınıyor",
  islem: "işlem",
  isleyis: "işleyiş",
  istediginiz: "istediğiniz",
  kalici: "kalıcı",
  karsilastiginiz: "karşılaştığınız",
  karsilastirma: "karşılaştırma",
  karsilastirirken: "karşılaştırırken",
  karsi: "karşı",
  karar: "karar",
  kayit: "kayıt",
  kaynagi: "kaynağı",
  kaynaklari: "kaynakları",
  kesif: "keşif",
  kisaca: "kısaca",
  kisa: "kısa",
  kisi: "kişi",
  kosullari: "koşulları",
  kotasi: "kotası",
  kredi: "kredi",
  kullanici: "kullanıcı",
  kullaniciya: "kullanıcıya",
  kullaniciyi: "kullanıcıyı",
  kullanicinin: "kullanıcının",
  kullanicilar: "kullanıcılar",
  kullanicilari: "kullanıcıları",
  kullanicilarin: "kullanıcıların",
  kullanicilariniz: "kullanıcılarınız",
  kullanim: "kullanım",
  kullanimi: "kullanımı",
  kullanimda: "kullanımda",
  kullaniminda: "kullanımında",
  kullanimini: "kullanımını",
  kullaniyorsunuz: "kullanıyorsunuz",
  kullandiginiz: "kullandığınız",
  kullandiktan: "kullandıktan",
  kullanilabilirlik: "kullanılabilirlik",
  kullanima: "kullanıma",
  kurumsal: "kurumsal",
  lutfen: "lütfen",
  memnuniyet: "memnuniyet",
  mesgul: "meşgul",
  mi: "mı",
  misiniz: "mısınız",
  musteri: "müşteri",
  musteriler: "müşteriler",
  musterilerin: "müşterilerin",
  nasil: "nasıl",
  netlestirici: "netleştirici",
  olacagi: "olacağı",
  olacak: "olacak",
  olcum: "ölçüm",
  olusmali: "oluşmalı",
  olusturdugunuz: "oluşturduğunuz",
  olusturdum: "oluşturdum",
  olustur: "oluştur",
  olustururken: "oluştururken",
  olusturmak: "oluşturmak",
  olusturmaniz: "oluşturmanız",
  olusturulacak: "oluşturulacak",
  olusturuldu: "oluşturuldu",
  olusuyor: "oluşuyor",
  onay: "onay",
  once: "önce",
  oncelik: "öncelik",
  oncelikli: "öncelikli",
  onem: "önem",
  onemli: "önemli",
  oneriler: "öneriler",
  oneri: "öneri",
  onerileri: "önerileri",
  ozellik: "özellik",
  ozellikleri: "özellikleri",
  ozellikle: "özellikle",
  ozel: "özel",
  ozet: "özet",
  paylastiginiz: "paylaştığınız",
  paylasilan: "paylaşılan",
  saglayan: "sağlayan",
  satin: "satın",
  secenek: "seçenek",
  secenekleri: "seçenekleri",
  secim: "seçim",
  secimi: "seçimi",
  sekilde: "şekilde",
  sekillendiriyor: "şekillendiriyor",
  sey: "şey",
  simdi: "şimdi",
  sinyal: "sinyal",
  sirada: "sırada",
  sirasinda: "sırasında",
  sonraki: "sonraki",
  sordugunuz: "sorduğunuz",
  soyle: "şöyle",
  soylediginiz: "söylediğiniz",
  sure: "süre",
  surec: "süreç",
  sureci: "süreci",
  surecinde: "sürecinde",
  surecini: "sürecini",
  sureleri: "süreleri",
  surtunme: "sürtünme",
  surukleyen: "sürükleyen",
  tasiyan: "taşıyan",
  tasiyor: "taşıyor",
  tek: "tek",
  tercih: "tercih",
  turkce: "Türkçe",
  turkcedir: "Türkçedir",
  tum: "tüm",
  uclu: "uçlu",
  urun: "ürün",
  urunde: "üründe",
  urunu: "ürünü",
  urunun: "ürünün",
  urununuz: "ürününüz",
  uzerinden: "üzerinden",
  uzerinde: "üzerinde",
  uzerine: "üzerine",
  uzun: "uzun",
  yuzde: "yüzde",
  yuzunden: "yüzünden",
  yuksek: "yüksek",
  yurur: "yürür",
  yurutme: "yürütme",
  yuz: "yüz",
};

const SPECIAL_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\baz once\b/gi, "az önce"],
  [/\bbuna gore\b/gi, "buna göre"],
  [/\bher sey\b/gi, "her şey"],
  [/\bne sekilde\b/gi, "ne şekilde"],
  [/\bnasil bir\b/gi, "nasıl bir"],
  [/\bnasil etkiledi\b/gi, "nasıl etkiledi"],
  [/\bnasil geciyor\b/gi, "nasıl geçiyor"],
  [/\bnasil calistigina\b/gi, "nasıl çalıştığına"],
  [/\bnasil calistigini\b/gi, "nasıl çalıştığını"],
  [/\bnasil tarif\b/gi, "nasıl tarif"],
  [/\bnasil yorumladiniz\b/gi, "nasıl yorumladınız"],
  [/\bsatin alma\b/gi, "satın alma"],
  [/\bson dusunceler\b/gi, "son düşünceler"],
  [/\bgorusme plani\b/gi, "görüşme planı"],
  [/\barastirma plani\b/gi, "araştırma planı"],
  [/\bkullanici arastirmasi\b/gi, "kullanıcı araştırması"],
];

const capitalized = (value: string) => {
  const [first = "", ...rest] = value;
  return `${first.toLocaleUpperCase("tr-TR")}${rest.join("")}`;
};

const matchCase = (match: string, replacement: string) => {
  if (match === match.toLocaleUpperCase("tr-TR")) {
    return replacement.toLocaleUpperCase("tr-TR");
  }

  const first = match[0];
  if (first && first === first.toLocaleUpperCase("tr-TR") && match.slice(1) === match.slice(1).toLocaleLowerCase("tr-TR")) {
    return capitalized(replacement);
  }

  return replacement;
};

const wordPattern = new RegExp(`\\b(${Object.keys(WORD_REPLACEMENTS).sort((a, b) => b.length - a.length).join("|")})\\b`, "gi");

export const restoreTurkishCharacters = (value: string) => {
  if (typeof value !== "string" || !value.trim()) {
    return "";
  }

  let nextValue = value;
  for (const [pattern, replacement] of SPECIAL_REPLACEMENTS) {
    nextValue = nextValue.replace(pattern, (match) => matchCase(match, replacement));
  }

  return nextValue.replace(wordPattern, (match) => {
    const replacement = WORD_REPLACEMENTS[match.toLocaleLowerCase("tr-TR")];
    return replacement ? matchCase(match, replacement) : match;
  });
};
