// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqdvwmwueaqyqepwyifk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxZHZ3bXd1ZWFxeXFlcHd5aWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjQwNTIsImV4cCI6MjA3MjUwMDA1Mn0.RFG2fRxBterLZPN4R-D4FSemymP5kmPQhUL6b4ppqk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});