// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elbokywmphjwmqunaoqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsYm9reXdtcGhqd21xdW5hb3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODc2OTUsImV4cCI6MjA3MTE2MzY5NX0.gmjoojnkfJ6sPUovkDGeYN52lJYvMBu8KZsckfEffTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});